# Generated by Django 5.2 on 2025-04-14 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_stock_articleid_stock_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='article',
        ),
    ]
