# Generated by Django 5.2 on 2025-05-04 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_remove_article_fournisseur_article_date_ajout_and_more'),
        ('stock', '0004_stock_article'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='etatStock',
            field=models.CharField(choices=[('en_alerte', 'En alerte'), ('hors_alerte', 'Hors alerte')], default='hors_alerte', max_length=15),
        ),
        migrations.AddField(
            model_name='stock',
            name='type',
            field=models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], default='entree', max_length=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stock',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.article'),
        ),
    ]
