# Generated by Django 5.2 on 2025-05-04 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0005_stock_date_stock_etatstock_stock_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateRapport', models.DateField()),
                ('vente', models.CharField(max_length=20)),
                ('approvisionnement', models.CharField(max_length=20)),
                ('type_rapport', models.CharField(choices=[('mensuel', 'Mensuel'), ('hebdomadaire', 'Hebdomadaire'), ('journalier', 'Journalier')], default='journalier', max_length=20)),
                ('contenu', models.TextField(default='')),
                ('généré_par', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
        ),
    ]
