# Generated by Django 5.2 on 2025-04-14 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_remove_commande_fournisseurid_commande_fournisseur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='fournisseur',
        ),
    ]
