# Generated by Django 5.2 on 2025-04-14 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_fournisseur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='fournisseur',
        ),
    ]
