# Generated by Django 5.2 on 2025-04-17 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_remove_article_fournisseur'),
        ('fournisseur', '0002_alter_fournisseur_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fournisseur.fournisseur'),
        ),
    ]
