# Generated by Django 5.2 on 2025-04-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_fournisseur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='quantiteInitiale',
        ),
        migrations.RemoveField(
            model_name='article',
            name='reference',
        ),
        migrations.AddField(
            model_name='article',
            name='categorie',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='references',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
