# Generated by Django 5.2 on 2025-05-04 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_article_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='fournisseur',
        ),
        migrations.AddField(
            model_name='article',
            name='date_ajout',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='etat',
            field=models.CharField(choices=[('en_stock', 'En stock'), ('hors_stock', 'Hors stock')], default='hors_stock', max_length=15),
        ),
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='references',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
