# Generated by Django 5.2 on 2025-05-04 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_remove_article_fournisseur_article_date_ajout_and_more'),
        ('fournisseur', '0002_alter_fournisseur_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='conditions_paiement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='numero_tva',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='adresse',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='contact',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='FournisseurArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseur.fournisseur')),
            ],
        ),
    ]
