# Generated by Django 5.1.7 on 2025-05-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userprofile_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('stock_manager', 'Stock Manager'), ('employe', 'Employé')], default='employe', max_length=30),
        ),
    ]
